export type Listing = {
  id: string;
  source_name: string;
  source_post_id: string;
  title_raw?: string | null;
  title: string;
  price_text?: string | null;
  price_value: number | null;
  price_per_m2: number | null;
  area_text?: string | null;
  area_m2: number | null;
  street_address: string | null;
  ward: string | null;
  full_address: string | null;
  map_reference_address?: string | null;
  province: string | null;
  district: string | null;
  latitude: number | null;
  longitude: number | null;
  geocode_precision: string | null;
  geocode_source?: string | null;
  geocode_display_name?: string | null;
  is_reference_coordinate: boolean;
  address_quality_score?: number | null;
  room_type: string | null;
  furnishing_level: string | null;
  image_count: number;
  primary_image_url: string | null;
  posted_at?: string | null;
  expired_at?: string | null;
  freshness_days?: number | null;
  contact_name?: string | null;
  contact_phone?: string | null;
  contact_zalo_url?: string | null;
  contact_facebook_url?: string | null;
  amenities_text?: string | null;
  amenity_count: number;
  has_aircon?: boolean;
  has_private_wc?: boolean;
  has_loft?: boolean;
  has_parking?: boolean;
  has_security?: boolean;
  has_fingerprint_lock?: boolean;
  allows_free_hours?: boolean;
  has_balcony?: boolean;
  has_kitchen?: boolean;
  has_fridge?: boolean;
  has_washer?: boolean;
  description_clean?: string | null;
  content_hash?: string | null;
  record_completeness_score: number | null;
  publication_quality_score?: number | null;
  has_direct_contact?: boolean;
  has_contact_name?: boolean;
  thumbnail_url: string | null;
  canonical_url: string;
  status: "active" | "expired" | "hidden";
  detail_path?: string | null;
  detail_source?: "static" | "supabase" | null;
};

export type ListingMapResponse = {
  total: number;
  returned: number;
  available_provinces: string[];
  geocode_summary: Record<string, number>;
  deploy_source_counts?: Record<string, number>;
  chunks?: string[];
  chunk_size?: number;
  detail_chunk_size?: number;
  dataset_mode?: string;
  dataset_version?: string;
  skipped_rows?: number;
  quality_summary?: {
    enabled: boolean;
    input_rows: number;
    valid_source_rows: number;
    qualified_rows: number;
    published_rows: number;
    rejected_invalid_source_rows: number;
    rejected_low_quality_rows: number;
    trimmed_rows: number;
    qualified_source_counts: Record<string, number>;
    published_source_counts: Record<string, number>;
    requirements: string[];
    ranking_preferences?: string[];
  };
  etl_summary?: EtlSummary;
  etl_runs?: EtlRun[];
  items: Listing[];
};

export type EtlSummary = {
  generated_at: string;
  status: "success" | "running" | "failed";
  source_rows: number;
  deduplicated_rows: number;
  duplicate_rows: number;
  rejected_rows: number;
  curated_rows: number;
  located_rows: number;
  exact_geocoded_rows: number;
  unresolved_geocode_rows: number;
  published_rows: number;
  duration_seconds?: number | null;
  source_counts: Record<string, number>;
  status_counts: Record<string, number>;
};

export type EtlRun = {
  date: string;
  generated_at: string;
  status: "success" | "running" | "failed";
  source_rows: number;
  curated_rows: number;
  rejected_rows: number;
  located_rows: number;
  published_rows: number;
  duration_seconds?: number | null;
};
