export type Listing = {
  id: string;
  source_name: string;
  source_post_id: string;
  title_raw?: string | null;
  title: string;
  price_text?: string | null;
  price_value: number | null;
  price_per_m2: number | null;
  area_text?: string | null;
  area_m2: number | null;
  street_address: string | null;
  ward: string | null;
  full_address: string | null;
  map_reference_address?: string | null;
  province: string | null;
  district: string | null;
  latitude: number | null;
  longitude: number | null;
  geocode_precision: string | null;
  geocode_source?: string | null;
  geocode_display_name?: string | null;
  is_reference_coordinate: boolean;
  address_quality_score?: number | null;
  room_type: string | null;
  furnishing_level: string | null;
  image_count: number;
  primary_image_url: string | null;
  posted_at?: string | null;
  expired_at?: string | null;
  freshness_days?: number | null;
  contact_name?: string | null;
  contact_phone?: string | null;
  contact_zalo_url?: string | null;
  contact_facebook_url?: string | null;
  amenities_text?: string | null;
  amenity_count: number;
  has_aircon?: boolean;
  has_private_wc?: boolean;
  has_loft?: boolean;
  has_parking?: boolean;
  has_security?: boolean;
  has_fingerprint_lock?: boolean;
  allows_free_hours?: boolean;
  has_balcony?: boolean;
  has_kitchen?: boolean;
  has_fridge?: boolean;
  has_washer?: boolean;
  description_clean?: string | null;
  content_hash?: string | null;
  record_completeness_score: number | null;
  thumbnail_url: string | null;
  canonical_url: string;
  status: "active" | "expired" | "hidden";
};

export type ListingMapResponse = {
  total: number;
  returned: number;
  available_provinces: string[];
  geocode_summary: Record<string, number>;
  deploy_source_counts?: Record<string, number>;
  chunks?: string[];
  chunk_size?: number;
  dataset_mode?: string;
  skipped_rows?: number;
  items: Listing[];
};
